apiVersion: v1
entries:
  k8s-pv-mount-point-exporter:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2025-09-09T21:57:28.711178664Z"
    description: Kubernetes PersistentVolume MountPoint Exporter
    digest: 0db2d60da1157b3161012d60e379a6d6611d414f309b4ec011d95c2900047e46
    name: k8s-pv-mount-point-exporter
    type: application
    urls:
    - k8s-pv-mount-point-exporter-1.0.1.tgz
    version: 1.0.1
generated: "2025-09-09T21:57:28.710716646Z"
