apiVersion: v1
entries:
  pv-mount-point-exporter:
  - apiVersion: v2
    appVersion: 0.1.8
    created: "2025-09-09T20:43:35.519223221Z"
    description: Signicat DevTools PersistentVolume MountPoint Exporter
    digest: 564024f83ba599c6769664ac541538f51e98cec9a46cc7bbf9a5a956678b70ee
    name: pv-mount-point-exporter
    type: application
    urls:
    - pv-mount-point-exporter-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v2
    appVersion: 0.1.7
    created: "2025-09-09T20:43:35.5188551Z"
    description: Signicat DevTools PersistentVolume MountPoint Exporter
    digest: 96c0d40b664dee99b3b65d8eb4f691e98fb9ca4f7e71aae1db04b085bb81e2e7
    name: pv-mount-point-exporter
    type: application
    urls:
    - pv-mount-point-exporter-0.1.7.tgz
    version: 0.1.7
generated: "2025-09-09T20:43:35.518455158Z"
