apiVersion: v1
entries:
  pv-mount-point-exporter:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-09-09T21:54:32.449007389Z"
    description: Signicat DevTools PersistentVolume MountPoint Exporter
    digest: 6b03eded9f79d259d3706a208370d6fc25f6593f8491e1341167672eb67c9d8a
    name: pv-mount-point-exporter
    type: application
    urls:
    - pv-mount-point-exporter-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v2
    appVersion: 0.1.10
    created: "2025-09-09T21:54:32.448545842Z"
    description: Signicat DevTools PersistentVolume MountPoint Exporter
    digest: c240353dc798866d19d88ee395823294b8dcb38ded256ecbbd629236622ed479
    name: pv-mount-point-exporter
    type: application
    urls:
    - pv-mount-point-exporter-0.1.10.tgz
    version: 0.1.10
generated: "2025-09-09T21:54:32.448063185Z"
