apiVersion: v2
name: pv-mount-point-exporter
description: Signicat DevTools PersistentVolume MountPoint Exporter

type: application

version: 0.1.9

appVersion: "0.1.9" # Will be used in GitHub Actions to set Container image tag and update helm chart "image.tag"
