apiVersion: v2
name: pv-mount-point-exporter
description: Signicat DevTools PersistentVolume MountPoint Exporter

type: application

version: 0.1.7

appVersion: "0.1.7" # Should match values.yaml image.tag
