apiVersion: v2
name: pv-mount-point-exporter
description: Signicat DevTools PersistentVolume MountPoint Exporter

type: application

version: 1.0.0

appVersion: "1.0.0" # Will be used in GitHub Actions to set Container image tag and update helm chart "image.tag"
