env:
  METRICS_LISTEN: ":8088"
image:
  repository: ghcr.io/signicat/k8s-pv-mount-point-exporter
  pullPolicy: Always
  tag: "0.1.8"
# Enable creation of ServiceMonitor object
serviceMonitor:
  enabled: true
metrics:
  port: 8088
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]
service:
  port: 80
resources:
  limits:
    #  cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
tolerations:
  # Tolerate anything
  - operator: "Exists"
affinity: {}
vmrule:
  enabled: false
