apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "my-app.fullname" . }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "my-app.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: list-and-get-storageclasses-and-nodes
  apiGroup: rbac.authorization.k8s.io