{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "my-app.fullname" . }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "my-app.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http-metrics
    path: /metrics
    # This part is required for services that live in the service mesh
    # These paths need to correspond to however SubSea team has configured Prometheus
    # And these values are working as of 2022-06-20
    scheme: https
    tlsConfig:
      caFile: /etc/prom-certs/root-cert.pem
      certFile: /etc/prom-certs/cert-chain.pem
      insecureSkipVerify: true
      keyFile: /etc/prom-certs/key.pem
{{- end }}
